'use strict';

module.exports = {
  pass: [
    {
      id: 'language/expressions/coalesce/basic.js',
      file: 'cases/pass/language/expressions/coalesce/basic.js',
      expected: [3, 7, 9],
    },
    {
      id: 'language/expressions/optional-chaining/member-chain.js',
      file: 'cases/pass/language/expressions/optional-chaining/member-chain.js',
      expected: [5, undefined, 4],
    },
    {
      id: 'language/expressions/optional-chaining/call.js',
      file: 'cases/pass/language/expressions/optional-chaining/call.js',
      expected: [3, undefined],
    },
    {
      id: 'language/expressions/template-literal/basic-substitution.js',
      file: 'cases/pass/language/expressions/template-literal/basic-substitution.js',
      expected: 'value=7',
    },
    {
      id: 'language/statements/variable/dstr/array-object-basic.js',
      file: 'cases/pass/language/statements/variable/dstr/array-object-basic.js',
      expected: 14,
    },
    {
      id: 'language/expressions/member/computed-set-get.js',
      file: 'cases/pass/language/expressions/member/computed-set-get.js',
      expected: { total: 7, key: 3 },
    },
    {
      id: 'language/expressions/array/index-growth.js',
      file: 'cases/pass/language/expressions/array/index-growth.js',
      expected: { first: 1, third: 4, size: 3 },
    },
    {
      id: 'language/statements/try/try-catch-finally-primitive.js',
      file: 'cases/pass/language/statements/try/try-catch-finally-primitive.js',
      expected: ['caught', 'ok', ['body', 'boom', 'finally', 'body', 'finally']],
    },
    {
      id: 'built-ins/Error/TypeError/name-message.js',
      file: 'cases/pass/built-ins/Error/TypeError/name-message.js',
      expected: { name: 'TypeError', message: 'boom' },
    },
    {
      id: 'built-ins/Array/isArray/basic.js',
      file: 'cases/pass/built-ins/Array/isArray/basic.js',
      expected: [true, false, -1],
    },
    {
      id: 'built-ins/Array/from/set-map-fn.js',
      file: 'cases/pass/built-ins/Array/from/set-map-fn.js',
      expected: [6, 8],
    },
    {
      id: 'built-ins/Array/prototype/sort/numeric-compare.js',
      file: 'cases/pass/built-ins/Array/prototype/sort/numeric-compare.js',
      expected: [-1, 1, 2, 3],
    },
    {
      id: 'built-ins/Math/max-abs-composition.js',
      file: 'cases/pass/built-ins/Math/max-abs-composition.js',
      expected: 7,
    },
    {
      id: 'built-ins/Object/fromEntries/basic.js',
      file: 'cases/pass/built-ins/Object/fromEntries/basic.js',
      expected: [['alpha', 'beta', 'gamma'], [1, 2, 3], 2, true],
    },
    {
      id: 'built-ins/String/prototype/matchAll/basic-groups.js',
      file: 'cases/pass/built-ins/String/prototype/matchAll/basic-groups.js',
      expected: [
        ['ab12', 'ab', '12', 0, 'ab'],
        ['cd34', 'cd', '34', 4, 'cd'],
      ],
    },
    {
      id: 'built-ins/Date/constructor/clone-getTime.js',
      file: 'cases/pass/built-ins/Date/constructor/clone-getTime.js',
      expected: [1234, 1234, -50],
    },
    {
      id: 'built-ins/Map/prototype/delete-clear.js',
      file: 'cases/pass/built-ins/Map/prototype/delete-clear.js',
      expected: [[['alpha', 3], ['beta', 2]], true, ['alpha'], 0],
    },
    {
      id: 'built-ins/Set/prototype/delete-clear.js',
      file: 'cases/pass/built-ins/Set/prototype/delete-clear.js',
      expected: [['alpha', 'beta'], true, [['alpha', 'alpha']], 0],
    },
    {
      id: 'built-ins/Promise/any/reject-errors.js',
      file: 'cases/pass/built-ins/Promise/any/reject-errors.js',
      expected: ['AggregateError', 'All promises were rejected', ['alpha', 'beta']],
    },
    {
      id: 'built-ins/BigInt/map-set-membership.js',
      file: 'cases/pass/built-ins/BigInt/map-set-membership.js',
      expected: ['7', 'left', true, 'bigint'],
    },
    {
      id: 'built-ins/RegExp/prototype/test-lastIndex.js',
      file: 'cases/pass/built-ins/RegExp/prototype/test-lastIndex.js',
      expected: [true, 2, false, 0],
    },
    {
      id: 'language/statements/function/recursion-factorial.js',
      file: 'cases/pass/language/statements/function/recursion-factorial.js',
      expected: 120,
    },
    {
      id: 'language/statements/for-of/array-basic.js',
      file: 'cases/pass/language/statements/for-of/array-basic.js',
      expected: [1, 2, 3],
    },
    {
      id: 'language/statements/for-of/map-destructuring.js',
      file: 'cases/pass/language/statements/for-of/map-destructuring.js',
      expected: ['alpha:1', 'beta:2'],
    },
    {
      id: 'language/expressions/call/member-this.js',
      file: 'cases/pass/language/expressions/call/member-this.js',
      expected: 42,
    },
    {
      id: 'language/statements/function/rest-parameters.js',
      file: 'cases/pass/language/statements/function/rest-parameters.js',
      expected: [1, 2, 2, 3],
    },
  ],
  unsupported: [
    {
      id: 'language/module-code/import-declaration/basic.js',
      file: 'cases/unsupported/language/module-code/import-declaration/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'module syntax is not supported',
      reason: 'Module syntax is outside the script-only v1 contract.',
    },
    {
      id: 'language/expressions/dynamic-import/basic.js',
      file: 'cases/unsupported/language/expressions/dynamic-import/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'dynamic import() is not supported',
      reason: 'Dynamic import is explicitly rejected by validation.',
    },
    {
      id: 'language/expressions/delete/basic.js',
      file: 'cases/unsupported/language/expressions/delete/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'delete is not supported in v1',
      reason: 'Property deletion is intentionally not part of the v1 surface.',
    },
    {
      id: 'language/statements/with/basic.js',
      file: 'cases/unsupported/language/statements/with/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'with is not supported',
      reason: 'The runtime only supports strict-mode execution.',
    },
    {
      id: 'language/statements/class/basic.js',
      file: 'cases/unsupported/language/statements/class/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'classes are not supported in v1',
      reason: 'Class semantics are outside the documented subset.',
    },
    {
      id: 'language/statements/generators/basic.js',
      file: 'cases/unsupported/language/statements/generators/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'generators are not supported in v1',
      reason: 'Generators and iterator protocol support are deferred.',
    },
    {
      id: 'language/statements/for-of/assignment-target.js',
      file: 'cases/unsupported/language/statements/for-of/assignment-target.js',
      errorKind: 'Validation',
      messageIncludes: 'for...of currently requires a let or const binding declaration',
      reason: 'The first iteration surface only supports let/const loop bindings.',
    },
    {
      id: 'language/statements/debugger/basic.js',
      file: 'cases/unsupported/language/statements/debugger/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'debugger statements are not supported',
      reason: 'Debugger hooks are excluded from the guest surface.',
    },
    {
      id: 'language/expressions/object/spread/basic.js',
      file: 'cases/unsupported/language/expressions/object/spread/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'object spread is not supported in v1',
      reason: 'Object spread remains outside the supported subset.',
    },
    {
      id: 'language/expressions/array/spread/basic.js',
      file: 'cases/unsupported/language/expressions/array/spread/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'array spread is not supported in v1',
      reason: 'Array spread remains outside the supported subset.',
    },
    {
      id: 'language/expressions/sequence/basic.js',
      file: 'cases/unsupported/language/expressions/sequence/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'sequence expressions are not supported in v1',
      reason: 'Sequence expressions are explicitly rejected in v1.',
    },
    {
      id: 'language/expressions/object/method-basic.js',
      file: 'cases/unsupported/language/expressions/object/method-basic.js',
      errorKind: 'Validation',
      messageIncludes: 'object literal methods are not supported in v1',
      reason: 'Object literal methods are part of the documented exclusions.',
    },
    {
      id: 'language/expressions/update/postfix.js',
      file: 'cases/unsupported/language/expressions/update/postfix.js',
      errorKind: 'Validation',
      messageIncludes: 'update expressions are not supported in v1',
      reason: 'Increment and decrement operators remain outside the supported subset.',
    },
    {
      id: 'language/expressions/template-literal/tagged-basic.js',
      file: 'cases/unsupported/language/expressions/template-literal/tagged-basic.js',
      errorKind: 'Validation',
      messageIncludes: 'tagged templates are not supported in v1',
      reason: 'Tagged template call semantics are explicitly deferred.',
    },
    {
      id: 'language/expressions/call/spread-args.js',
      file: 'cases/unsupported/language/expressions/call/spread-args.js',
      errorKind: 'Validation',
      messageIncludes: 'spread arguments are not supported in v1',
      reason: 'Call-argument spreading is explicitly rejected by validation.',
    },
    {
      id: 'language/expressions/assignment/destructuring-array.js',
      file: 'cases/unsupported/language/expressions/assignment/destructuring-array.js',
      errorKind: 'Validation',
      messageIncludes: 'destructuring assignment is not supported in v1',
      reason: 'Only declaration-time destructuring is supported today.',
    },
    {
      id: 'language/expressions/member/private-field.js',
      file: 'cases/unsupported/language/expressions/member/private-field.js',
      errorKind: 'Validation',
      messageIncludes: 'private fields are not supported in v1',
      reason: 'Private names are outside the documented guest subset.',
    },
    {
      id: 'language/expressions/meta-property/new-target.js',
      file: 'cases/unsupported/language/expressions/meta-property/new-target.js',
      errorKind: 'Validation',
      messageIncludes: 'meta properties are not supported',
      reason: 'Meta properties such as new.target are currently rejected.',
    },
    {
      id: 'language/expressions/binary/instanceof-basic.js',
      file: 'cases/unsupported/language/expressions/binary/instanceof-basic.js',
      errorKind: 'Validation',
      messageIncludes: 'unsupported binary operator in v1',
      reason: 'instanceof remains outside the v1 operator surface.',
    },
    {
      id: 'language/expressions/unary/bitwise-not.js',
      file: 'cases/unsupported/language/expressions/unary/bitwise-not.js',
      errorKind: 'Validation',
      messageIncludes: 'unsupported unary operator in v1',
      reason: 'Bitwise operators are intentionally excluded from the supported subset.',
    },
    {
      id: 'language/expressions/assignment/exponentiate-assign.js',
      file: 'cases/unsupported/language/expressions/assignment/exponentiate-assign.js',
      errorKind: 'Validation',
      messageIncludes: 'unsupported assignment operator in v1',
      reason: 'Assignment operators remain limited to the documented small set.',
    },
    {
      id: 'language/expressions/object/computed-key.js',
      file: 'cases/unsupported/language/expressions/object/computed-key.js',
      errorKind: 'Validation',
      messageIncludes: 'unsupported property key in v1',
      reason: 'Object literal property keys remain limited to static identifier, string, and numeric keys.',
    },
    {
      id: 'language/statements/variable/var-basic.js',
      file: 'cases/unsupported/language/statements/variable/var-basic.js',
      errorKind: 'Validation',
      messageIncludes: 'only let and const are supported',
      reason: 'The supported declaration surface intentionally excludes var.',
    },
    {
      id: 'language/statements/for-await-of/basic.js',
      file: 'cases/unsupported/language/statements/for-await-of/basic.js',
      errorKind: 'Validation',
      messageIncludes: 'for await...of is not supported',
      reason: 'Async iterator control flow is not in the current subset.',
    },
    {
      id: 'language/expressions/ambient-global/process.js',
      file: 'cases/unsupported/language/expressions/ambient-global/process.js',
      errorKind: 'Validation',
      messageIncludes: 'forbidden ambient global `process`',
      reason: 'Ambient host globals are rejected when lexical resolution leaves them unresolved.',
    },
    {
      id: 'language/expressions/call/free-eval.js',
      file: 'cases/unsupported/language/expressions/call/free-eval.js',
      errorKind: 'Validation',
      messageIncludes: 'forbidden ambient global `eval`',
      reason: 'Free eval is explicitly rejected during validation.',
    },
  ],
};
