/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cancelCancellationToken(tokenId: string): void

export declare function claimProgressSnapshot(snapshotIdentity: string): boolean

export declare function compileProgram(source: string): Buffer

export declare function createCancellationToken(): string

export declare function inspectSnapshot(snapshot: Buffer, policyJson: string): string

export declare function isProgressSnapshotUsed(snapshotIdentity: string): boolean

export declare function releaseCancellationToken(tokenId: string): void

export declare function resumeProgram(snapshot: Buffer, payloadJson: string, policyJson: string, cancellationTokenId?: string | undefined | null): string

export declare function snapshotIdentity(snapshot: Buffer): string

export declare function startProgram(program: Buffer, optionsJson: string, cancellationTokenId?: string | undefined | null): string
