mod property_support;

use mustard::{
    ExecutionOptions, compile, dump_program, execute, load_program, lower_to_bytecode, start,
    start_bytecode,
};
use proptest::prelude::*;

use property_support::{completed_value, supported_program_strategy};

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 64,
        .. ProptestConfig::default()
    })]

    #[test]
    fn generated_programs_round_trip_through_bytecode_and_serialization(
        source in supported_program_strategy(),
    ) {
        let compiled = compile(&source)
            .unwrap_or_else(|error| panic!("generated program should compile:\n{source}\n{error}"));
        let direct = execute(&compiled, ExecutionOptions::default())
            .unwrap_or_else(|error| panic!("generated program should execute:\n{source}\n{error}"));

        let bytecode = lower_to_bytecode(&compiled)
            .unwrap_or_else(|error| panic!("generated program should lower:\n{source}\n{error}"));
        let dumped = dump_program(&bytecode)
            .unwrap_or_else(|error| panic!("generated bytecode should serialize:\n{source}\n{error}"));
        let loaded = load_program(&dumped)
            .unwrap_or_else(|error| panic!("serialized program should load:\n{source}\n{error}"));
        let loaded_result = completed_value(
            start_bytecode(&loaded, ExecutionOptions::default())
                .unwrap_or_else(|error| panic!("loaded program should start:\n{source}\n{error}")),
        );
        let started_result = completed_value(
            start(&compiled, ExecutionOptions::default())
                .unwrap_or_else(|error| panic!("compiled program should start:\n{source}\n{error}")),
        );

        prop_assert_eq!(&direct, &loaded_result, "source: {}", source);
        prop_assert_eq!(&direct, &started_result, "source: {}", source);
    }
}
